#include <opencv2/opencv.hpp>
#include <opencv2/highgui/highgui.hpp>

#include <iostream>
#include <sstream>

using namespace cv;
using namespace std;

// Global variables
Mat frame; //current frame
Mat fgMaskMOG2; //fg mask fg mask generated by MOG method
Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor
int keyboard; //input from keyboard

int main()
{
	namedWindow("Frame", WINDOW_NORMAL);
	namedWindow("FG Mask MOG2", WINDOW_NORMAL);

	pMOG2 = createBackgroundSubtractorMOG2();

	string firstFrameFileName = "blankboard.jpg";
	string secondFrameFileName = "finalboard.jpg";

	frame = imread(firstFrameFileName);
	if (frame.empty()) {
		//error in opening the first image
		cerr << "Unable to open first image frame: " << firstFrameFileName << endl;
		exit(EXIT_FAILURE);
	}

	//update the background model
	pMOG2->apply(frame, fgMaskMOG2);
	//show the current frame and the fg masks
	imshow("Frame", frame);
	imshow("FG Mask MOG2", fgMaskMOG2);
		
	//read the next frame
	frame = imread(secondFrameFileName);
	if (frame.empty()) {
		//error in opening the next image in the sequence
		cerr << "Unable to open image frame: " << secondFrameFileName << endl;
		exit(EXIT_FAILURE);
	}

	//update the background model
	pMOG2->apply(frame, fgMaskMOG2);
	//show the current frame and the fg masks
	imshow("Frame", frame);
	imshow("FG Mask MOG2", fgMaskMOG2);

	waitKey(0);

	return EXIT_SUCCESS;
}

